steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/dark-throne-464103-h1/cloud-run-source-deploy/alurabackend:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/dark-throne-464103-h1/cloud-run-source-deploy/alurabackend:latest']
  - name: 'gcr.io/cloud-builders/gcloud' # Paso para desplegar en Cloud Run
    args:
      - 'run'
      - 'deploy'
      - 'alurabackend-service' # Nombre de tu servicio de Cloud Run
      - '--image'
      - 'us-central1-docker.pkg.dev/dark-throne-464103-h1/cloud-run-source-deploy/alurabackend:latest'
      - '--region'
      - 'us-central1' # Tu región
      - '--service-account'
      - 'alurabackend-run-sa@dark-throne-464103-h1.iam.gserviceaccount.com' # Email completo de tu SA de Cloud Run
      - '--allow-unauthenticated' # Permite acceso público si es tu intención
      - '--platform'
      - 'managed'
      - '--project'
      - 'dark-throne-464103-h1' # Tu ID de proyecto
images:
  - 'us-central1-docker.pkg.dev/dark-throne-464103-h1/cloud-run-source-deploy/alurabackend:latest'

options: # <--- ¡Añade esta sección!
  logging: CLOUD_LOGGING_ONLY # Esto resuelve el error del log